version: '3.9'

services:
  shop:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop
    container_name: shop
    env_file: .env
    restart: unless-stopped
    expose:
      - 4000
    ports:
      - '4001:4000'
    volumes:
      - .:/app
    command: npm run dev
