version: '3.9'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    env_file: .env
    restart: unless-stopped
    expose:
      - 4000
    ports:
      - '4001:4000'
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - app-network
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email --agree-tos --no-eff-email --staging -d   -d #TODO
volumes:
  # certbot-etc:
  # certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ #TODO
      o: bind

networks:
  app-network:
    driver: bridge
