version: '3.9'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    env_file: .env
    restart: unless-stopped
    expose:
      - 4000
    ports:
      - '4001:4000'
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - app
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app
networks:
  app:
    external: true
