version: '3.9'

services:
  shop:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: shop
    env_file:
      - .env
    expose:
      - 4000
    ports:
      - '4000:4000'
    command: npm run start
