version: '3.9'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    env_file: .env
    restart: unless-stopped
    ports:
      - '4000:4000'
    command: npm run dev
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
    networks:
      - app-network

networks:
  app-network:
